<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ArchitectureMetamodel" nsURI="eu.modelwriter.demonstrations.metamodels.architecture" nsPrefix="arch">
  <eAnnotations source="http://www.modelwriter.eu/alloyinecore/import">
    <details key="Ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.modelwriter.eu/alloyinecore/source">
    <details key="source" value="import Ecore : 'http://www.eclipse.org/emf/2002/Ecore';&#xA;&#xA;package ArchitectureMetamodel : arch = 'eu.modelwriter.demonstrations.metamodels.architecture'&#xA;{&#xA;    public class one ArchitectureMetamodel&#xA;    {&#xA;        attribute name : String[?];&#xA;        property some elements : ArhitecturalElement[*] { ordered composes };&#xA;    }&#xA;    abstract class ArhitecturalElement [3]&#xA;    {&#xA;        attribute id : Integer[?];&#xA;        attribute name : String[?];&#xA;    }&#xA;    class Component extends ArhitecturalElement&#xA;    {&#xA;        property subComponents : Component[*] { ordered composes transitive acyclic };&#xA;    }&#xA;}"/>
    <details key="source_hash" value="-550004049"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureMetamodel">
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
      <details key="visibility" value="public"/>
    </eAnnotations>
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/cardinality">
      <details key="cardinality" value="one"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1" eType="//ArhitecturalElement" containment="true">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/cardinality">
        <details key="cardinality" value="some"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArhitecturalElement" abstract="true">
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/reasoning/lowerscope">
      <details key="lowerscope" value="3"/>
    </eAnnotations>
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/reasoning/upperincluded">
      <details key="lowerincluded" value="["/>
    </eAnnotations>
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/reasoning/lowerincluded">
      <details key="upperincluded" value="]"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="//ArhitecturalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subComponents" upperBound="-1" eType="//Component" containment="true">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/transitive"/>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/acyclic"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
