<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generics" nsURI="eu.modelwriter.generics" nsPrefix="gns">
  <eClassifiers xsi:type="ecore:EClass" name="List" abstract="true">
    <eTypeParameters name="E"/>
    <eOperations name="add">
      <eParameters name="element" lowerBound="1">
        <eGenericType eTypeParameter="#//List/E"/>
      </eParameters>
    </eOperations>
    <eOperations name="iterator">
      <eGenericType eClassifier="#//Iterator">
        <eTypeArguments eTypeParameter="#//List/E"/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Iterator">
    <eTypeParameters name="E"/>
    <eOperations name="next">
      <eGenericType eTypeParameter="#//Iterator/E"/>
      <eGenericExceptions eClassifier="#//MyException">
        <eTypeArguments eTypeParameter="#//Iterator/E"/>
      </eGenericExceptions>
    </eOperations>
    <eOperations name="hasNext" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayList">
    <eTypeParameters name="V"/>
    <eGenericSuperTypes eClassifier="#//List">
      <eTypeArguments eTypeParameter="#//ArrayList/V"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Car"/>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Owner">
    <eTypeParameters name="K"/>
    <eTypeParameters name="V">
      <eBounds eClassifier="#//Person"/>
      <eBounds eClassifier="#//Car"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cars">
      <eGenericType eClassifier="#//ArrayList">
        <eTypeArguments eClassifier="#//Car"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner">
      <eGenericType eTypeParameter="#//Owner/V"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shape" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Canvas">
    <eOperations name="draw" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="shapes" lowerBound="1">
        <eGenericType eClassifier="#//List">
          <eTypeArguments>
            <eUpperBound eClassifier="#//Shape"/>
          </eTypeArguments>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="create">
      <eTypeParameters name="V">
        <eBounds eClassifier="#//Shape"/>
      </eTypeParameters>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="create">
      <eParameters name="arg">
        <eGenericType eClassifier="#//ArrayList">
          <eTypeArguments>
            <eLowerBound eClassifier="#//Canvas"/>
          </eTypeArguments>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref">
      <eGenericType eClassifier="#//List">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyException">
    <eTypeParameters name="T"/>
  </eClassifiers>
</ecore:EPackage>
